#!/bin/bash
echo "================================================"
echo "🔄 Restarting Development Servers"
echo "================================================"
echo ""
echo "1. Stop semua server yang sedang berjalan (Ctrl+C)"
echo "2. Jalankan script ini di 2 terminal berbeda:"
echo ""
echo "📍 Terminal 1 - Backend:"
echo "   cd /home/hasanarofid/Documents/solkit/proyek/alazhar/php-backend"
echo "   php -S localhost:8000 -t public"
echo ""
echo "📍 Terminal 2 - Frontend:"
echo "   cd /home/hasanarofid/Documents/solkit/proyek/alazhar/react-frontend"
echo "   npm run dev"
echo ""
echo "3. Setelah server restart, buka browser:"
echo "   - Clear cache (Ctrl+Shift+Delete)"
echo "   - Hard reload (Ctrl+Shift+R)"
echo "   - Buka: http://localhost:5173/admin/sliders"
echo ""
echo "================================================"
